### PR TITLE
Added Red Dog w/Fire

### PR DESCRIPTION
**Pull request by EricEnergy**
### Description 

- Added gifs for a new dog

- Updated code to allow for user to choose a red dog under the search bar

### CODE REVIEW

**Comment by tonybaloney** [comment]
Wow, ok. What's the story here, why is the dog on fire?

**Comment by EricEnergy** [comment]
> Wow, ok. What's the story here, why is the dog on fire?

In a way he's a hell hound. So not really on fire but controls fire. Almost like flairion from pokemon. Just a cool idea I had to show off to people at work who said that I should submit it so I thought I would.

**Comment by tonybaloney** [comment]
screenshot 2022-10-21 at 16 36 54
The image is cropped so the tip of the flames is missing, are you able to fix that?

**Comment by EricEnergy** [comment]
> screenshot 2022-10-21 at 16 36 54 [ screenshot 2022-10-21 at 16 36 54 ](https://user-images.githubusercontent.com/1532417/197121046-ccf8351b-a8cc-4858-8510-3990a639a2c5.gif) [ ](https://user-images.githubusercontent.com/1532417/197121046-ccf8351b-a8cc-4858-8510-3990a639a2c5.gif) The image is cropped so the tip of the flames is missing, are you able to fix that?

Sorry for the wait @tonybaloney Not sure why all the gifs got cropped but all gifs have been updated!

**Review by tonybaloney — APPROVED** [review]

**Comment by tonybaloney** [comment]
Thanks for the contribution, it'll be available in the next release

**Pull request merged**
