### PR TITLE
Name tags for pets

### PR DESCRIPTION
**Pull request by Technickel-Dev**
I was having a hard time remembering who was who without doing a roll call, so I decided to make it easier! This push adds a setting that allows you to turn on name tags for your pets. By default it is set to false, so they don't show because with a lot of pets it can get messy. The name tag will disappear during the duration of a speech bubble.

Also a few super small code cleanups thrown in (mainly using CSS variables for font size and DRYing up pet initialization.

A future improvement might be to offset the name by a random amount so they all don't overlap on the same plane. There is also some probably clever way of reading the length of a name and changing the `left` offset to center the text, but my brain couldn't figure it out for the time being.

This is my first time touching VSCode extension code directly, so feel free to give as much feedback as you want!
image

### CODE REVIEW

**Comment by tonybaloney** [comment]
Love this! Try out the roll call command and let me know how they could work together

**Comment by Technickel-Dev** [comment]
Since the rollout command is a notification thing, I find it doesn't really interact much with this name tag feature.

The only thing I could think of that would be nice for them to work together would be hiding all name tags and then having the single one pop up when their name is roll called. I would have to write the code to "stagger" the roll call notifications and maybe hide the notification after a short amount of time (if that's even possible, not sure) I would suggest that interaction could be a separate feature, if you want it.

Also just noticed a branch conflict, lots of PRs! Fixed that up. Let me know what path you want to take.

**Comment by tonybaloney** [comment]
I'll test and review this properly tomorrow, in the meantime please resolve the conflict

**Comment by Technickel-Dev** [comment]
Conflict resolved!

**Pull request closed without merging**
