### PR TITLE
Add cockatiel as a new pet

### PR DESCRIPTION
**Pull request by marcduiker**
~I'm waiting for a few more names and then I'll make this PR final.~
Ready for review

### CODE REVIEW

**Comment by tonybaloney** [comment]
Is the bird bound to the floor like the other pets or will it fly about?

**Comment by marcduiker** [comment]
> Is the bird bound to the floor like the other pets or will it fly about?

Since I only made drawings for walking it's bound to the floor 😅.

**Comment by tonybaloney** [comment]
👍🏻

**Comment by tonybaloney** [comment]
love this. great work as always ❤️ 🦜

**Pull request merged**
