### PR TITLE
Added pet interaction, Dynamic throwing!

### PR DESCRIPTION
**Pull request by Luke-G-Cordova**
# Dynamic Throwing!

- Added ball interaction with the mouse via a toggle. 
- A user can still choose the original throw ball functionality but if they need a little more interactivity with the ball and their pets, they can toggle on the dynamic option. This allows the user to click and drag on the canvas to throw the ball in any direction.

I really like and enjoy this extension but I felt the need to have more interaction with my pets. Let me know if I breached any formatting for this project or you find any bugs with my code, Ill try to fix them when I can.

This feature contributes to #137

### CODE REVIEW

**Comment by Luke-G-Cordova** [comment]
Also, I'm sorry I didn't make an issue for this I totally forgot. If you need me to make one and link it to this PR let me know.

**Comment by Luke-G-Cordova** [comment]
@tonybaloney I see that Codecov did not like my pull request, what do I need to fix to get this request merged?

**Comment by tonybaloney** [comment]
Dw about the coverage report. 
I've tried to use this and I can't get it working. 
I think the 3 commands should be removed and replaced with a single configuration setting. It's confusing to have settings configured via commands. 

You can propagate settings via the send message (as a parameter) or when the panel starts up.

**Comment by Luke-G-Cordova** [comment]
@tonybaloney You are totally right about that, thanks for the feedback. I originally constructed the functionality in a way that would depend on the 3 commands but eventually realized it only needed the one and for some reason I just kept the other 2 despite their unneeded complexity. I'll fix it and let you know when it's ready. 
As for getting it to work, there should be a button to the right of the throw ball button with the same icon just above the area where you are currently displaying the pets. It is in between the add pet and delete pet buttons currently. This button acts as a toggle and pressing it once allows you to then drag your mouse across the canvas to 'throw' the ball. You can continue to throw the ball in different directions with different velocities by dragging your mouse. This works until you click the toggle again. After this point the extension functions as normal. I will get you a small video demonstration soon to clarify this point more because I can see how it may be confusing to figure out at first because I did not design any special icon or make a style that changes the color of the toggle when it is toggled. Hope this helps for now.

**Comment by Luke-G-Cordova** [comment]
https://user-images.githubusercontent.com/67668950/200303566-62fe30f3-657b-4a58-8f01-e1e404583f44.mov

Every time I am hovering over the icon, I am clicking it. This either enables me to drag my mouse to throw the ball or disables that ability depending on the previous state of that toggle.

**Comment by Luke-G-Cordova** [comment]
I haven't figured out a good way of showing the user that the button is toggled on or off yet because I do not have a lot of experience in the world of vscode extensions yet. I looked at some documentation and decided Id try to find a better solution later. If you have some insight as to how I might go about achieving this goal I'd love to hear it!

**Comment by Luke-G-Cordova** [comment]
Im thinking about taking the button out altogether and just forcing the user to execute the command via the command pallet or binding it to a key binding. What are your thoughts @tonybaloney ?

**Comment by Luke-G-Cordova** [comment]
https://user-images.githubusercontent.com/67668950/200444269-b98907a9-dc90-4d77-bb26-a9039d1f98b4.mov

@tonybaloney I decided to just make it a command instead of also binding the command to a button in the action toolbar. The command is `vscode-pets.toggle-dynamic-throw` and executing it should enable the ability to throw a ball with the mouse. Executing the command a second time will turn this feature off and allow the extension to operate as normal. I hope this explanation helps and simplifies things! This should be good to merge when you are ready.

**Comment by Luke-G-Cordova** [comment]
@tonybaloney were you ever able to get this working on your local?

**Comment by tonybaloney** [comment]
Sorry, I've been really busy. Got it working this time. Love the behaviour and it makes it a lot more fun to be able to lob the ball sideways. 

screenshot 2022-11-20 at 18 10 15

Some feedback--

1. I don't think it's obvious what "dynamic throwing" means to the user. "Throw ball with mouse" might be more obvious?
2. The toggled state should be a configuration setting in [configuration properties](https://github.com/tonybaloney/vscode-pets/blob/master/package.json#L122-L124), not a global state within the panel that needs to be toggled by a command. There are a few reasons for this:

  * It's not persistent, if the panel shows/hides it'll reset the state and it's not obvious why you can't suddenly throw with the ball
  * It's not obvious what the current state is (am I toggling it on or off?) unless you throw the ball
  * Every time you restart VS Code (well actually, just close the panel) you have to run the command again

You can reuse the toggle action code by adding a watch to the configuration option, like [this](https://github.com/tonybaloney/vscode-pets/blob/master/src/extension/extension.ts#L585-L587). You'll need to have some logic in [activate](https://github.com/tonybaloney/vscode-pets/blob/master/src/extension/extension.ts#L267) to set the state to whatever is configured by the user. 

For (2) I understand that's a bit more work and you've already done a lot to get this feature built, so I can merge as-is and change it to a configuration setting for you if you want?

**Comment by Luke-G-Cordova** [comment]
Hey I really appreciate your feedback! I think you are right about the "dynamic throwing" name, I chose something quick and easy so I could get to the development stuff. "Throw ball with mouse" or "Throw with mouse" would definitely be more user friendly. 
As for the global states, I ran into the same problems you mention. It is my first time working on a vscode extension and I didn't really know how to go about fixing them even after some google searches. I am totally willing to take a stab at it given your new tips but I do feel like you know the organizational flow that this project is going for a little better than I do currently. 
I am totally ok if you'd like to merge as-is and change it to a configuration setting! Let me know if you need me to change it to a config setting and Ill do my best. I'm definitely going to look over the code if you do decide to do it because I am curious and it'll help in the future if I contribute more.
Again, thanks for the feedback!

**Comment by tonybaloney** [comment]
@Luke-G-Cordova In that case, I'll merge this and then raise another PR to demonstrate the change and ask for your review on that PR.

**Pull request merged**
