### PR TITLE
Setup Crowdin

### PR DESCRIPTION
**Pull request by andrii-bodnar**
Hey everyone,

Recently I found this extension and now it's my favorite VS Code Extension ever 😍 

image

Just did some analysis of the current i18n workflow and it feels like GitHub issues and PRs reported by the community are not so easy to handle. The community translators can work together in Crowdin, translations would be delivered as PR and volunteers can raise issues for problematic strings via Crowdin.

I'm suggesting the integration with Crowdin via GitHub Actions. Crowdin is **free for open-source** projects. This integration works in the following way:

- the action runs every 6 hours (actually, it's up to you what trigger to use, it could also be a push to the default branch, for example)
- upload new source texts to the Crowdin project
- upload existing translations to Crowdin
- download all the new translations from Crowdin, commit changes and open a Pull Request.

You can find my demo Crowdin project here - [vs-code-pets-demo](https://crowdin.com/project/vs-code-pets-demo).

Example of the first PR that will be created by the Action - [here](https://github.com/andrii-bodnar/vscode-pets/pull/1/commits/02a89c273b8d033c5fe51c93180a4347d86bcaca) (Don't worry about the diffs - it's just updated the translation files to the actual state. The next PRs will include the new translations only).

Also, I would be happy to contribute to Ukrainian translations 🇺🇦

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
**The next steps we can do to move further with this integration:**
- Create a [Crowdin](https://accounts.crowdin.com/register) account.
- Submit the [Open-source project setup request form](https://crowdin.com/page/open-source-project-setup-request).
- Create a new Crowdin Project:
  - Select the source language.
  - Fill in other target languages.
  - In the project settings enable the global Translation Memory (optional).
- Generate a new Personal Access Token in your Crowdin account settings.
- Generate a new GitHub Token (only the `repo` scope is required).
- Create the Actions secrets for your repository:
  - `CROWDIN_PERSONAL_TOKEN` - the personal access token generated in Crowdin.
  - `CROWDIN_PROJECT_ID` - ID of the Crowdin project.
  - `GH_TOKEN` - the personal access token generated in GitHub.
- merge this PR.

**Comment by tonybaloney** [comment]
Thanks Andrii, I'll take a look at this. The localisation API in VS Code is changing in the latest release, so I need to move to the latest package, see #276

**Comment by tonybaloney** [comment]
The related PR is merged now, `package.nls.json` is still there, but isn't used for translations.

The `l10n/` directory now keeps the mapping between English and the target languages.

**Review by tonybaloney — APPROVED** [review]

**Comment by tonybaloney** [comment]
This is the new project. https://crowdin.com/project/vscode-pets

**Pull request merged**
