### PR TITLE
Add new pet chicken

### PR DESCRIPTION
**Pull request by MhouneyLH**
This is connected to issue #242 

I changed all necessary things. (or at least I think that I have done this) I tested it and the extension creates the chicken, but it does not get displayed in the frame. Now I don't really know what to do anymore to get it working. :/

Additionally I get errors from the translation files, but I guess, that this has nothing to do with the new chicken-pet.
image

### CODE REVIEW

**Comment by tonybaloney** [comment]
Make sure you're running a newer version of vs code. Also open up the Developer Console to see any runtime errors

**Comment by MhouneyLH** [comment]
I forgot to compile the whole project and because of this the chicken could not load. 😂

**Comment by gulyapulya** [comment]
Love your chicken names list,  'Albert Eggstein' 😂 this is masterpiece 🤌🏼

**Comment by tonybaloney** [comment]
Love it!! 👍🏻

**Review by tonybaloney — APPROVED** [review]

**Pull request merged**
