### PR TITLE
Add the ability to set a custom name for a pet

### LINKED ISSUE #173: Add the ability to set a custom name for a pet
When adding a pet, it should auto-assign a name or give the ability to set a custom name

### PR DESCRIPTION
**Pull request by ccjmne**
Resolves #173.

I added an additional step to the `vscode-pets.spawn-pet` command, which allows the user to input any name they want for their pets.

It automatically suggests a random name from the appropriate list (according to the corresponding `PetType`) and pre-selects it, so the user may just start typing to overwrite the suggestion.
Leaving the field blank behaves as previously, generating a random name for the new pet.

### CODE REVIEW

**Comment by ccjmne** [comment]
The code could be much more elegant by resolving #161.

**Comment by tonybaloney** [comment]
screenshot 2022-10-05 at 14 44 35

I just tested switching the session from explorer to panel and it causes this issue because PetSpecification accepts null values and older versions won't have persisted the name to the disk. I'll refactor your random name selector into a function that'll be called when name is undefined.

**Comment by tonybaloney** [comment]
I'm working on testing how the states are persisted and recovers. I'll push a patch to this branch as it wasn't introduced in this PR

**Comment by ccjmne** [comment]
> I just tested switching the session from explorer to panel and it causes this issue because PetSpecification accepts null values and older versions won't have persisted the name to the disk. I'll refactor your random name selector into a function that'll be called when name is undefined.

Oh, wow! I ran the tests and everything but didn't think of that.
Thank you for being thorough!

**Comment by tonybaloney** [comment]
Brilliant contribution. Good luck with the rest of hacktoberfest

**Pull request merged**
