### PR TITLE
Rat pet

### PR DESCRIPTION
**Pull request by piotrszleg**
Adds rat as a pet type.

Rats roam around and jump when hovered over.

They can chase a ball, but don't climb on walls.

There are three rat colors
- gray
- white with red eyes
- brown (mixed brown head and white body)

gray rat

white rat

brown rat

editor screenshot

Related to issue #28

### CODE REVIEW

**Comment by piotrszleg** [comment]
run

**Comment by piotrszleg** [comment]
@tonybaloney maybe you missed the notification about this pull request changing status from draft, so I added a mention.

**Comment by tonybaloney** [comment]
Thanks. I'm on holiday for a few weeks. I'll take a look when I'm back

**Comment by piotrszleg** [comment]
I fixed an error in the merged package.json that caused the pipelines to fail,

**Comment by tonybaloney** [comment]
Love it. 👍🏻

**Review by tonybaloney — APPROVED** [review]

**Pull request merged**
