### PR TITLE
Update name cursor to be per pet type

### PR DESCRIPTION
**Pull request by JING1201**
Resolves https://github.com/tonybaloney/vscode-pets/issues/56

This PR adds a static counter for each Pet class which can be used as a cursor for the name. 
Note that cats and dogs share the same name list, so their cursor is based on the sum of the count of cats and dogs.

### CODE REVIEW

**Comment by JING1201** [comment]
@tonybaloney Is it necessary to add the values of these static counters to the `state`? The current code works fine on my machine, but I wasn't sure what should be covered by `state`.

**Comment by tonybaloney** [comment]
> @tonybaloney Is it necessary to add the values of these static counters to the `state`? The current code works fine on my machine, but I wasn't sure what should be covered by `state`.

State is used when closing and recovering the tab. Try using the panel mode and then closing the panel. it should remember the names of the pets

**Comment by JING1201** [comment]
> > @tonybaloney Is it necessary to add the values of these static counters to the `state`? The current code works fine on my machine, but I wasn't sure what should be covered by `state`.
> 
> State is used when closing and recovering the tab. Try using the panel mode and then closing the panel. it should remember the names of the pets

Thank you! Just tested closing and re-opening the panel, and the static counters for each Pet type is maintained. The functionality should be good to go, but let me know if you have other comments on my code :)

**Comment by tonybaloney** [comment]
Thanks @JING1201 ! this is a great contribution

**Pull request merged**
