### PR TITLE
Webview view

### LINKED ISSUE #12: Pet panel in other views
Many times out of habit I hit the button to close all the panels / tabs and accidentally close the one for the pet.

I would like the option to be able to move the panel to other view types and to be able to have my pet in the sidebar without having to worry about accidentally closing it.

I have tried to make a concept to explain it better.
Example concept

I have found the following about this in the documentation:
* [WebviewView](https://code.visualstudio.com/api/references/vscode-api#WebviewView).
* [WebviewView Example](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-view-sample).

### PR DESCRIPTION
**Pull request by Yukaii**
resolves #12 

## Screenshots

<details>
<summary>Click to expand screencasts</summary>

<h3>Add new position setting (`panel` & `explorer`)</h3>

https://user-images.githubusercontent.com/4230968/112988987-0979d280-9197-11eb-9a6c-1eb24188b199.mp4

<h3>Add "throw ball" and "Spawn pets" command to view title menu</h3>

https://user-images.githubusercontent.com/4230968/112989012-0d0d5980-9197-11eb-9d93-67d4a81d97c6.mp4

<h3>Add new "Reset pets" command, since there's no actual reload for webview view</h3>

https://user-images.githubusercontent.com/4230968/112989021-0ed71d00-9197-11eb-9566-b59e31aefabe.mp4

</details>

### Changes

- Add a new class `PetWebviewContainer` shared webview logic for panel webview and webview view. 
- Add new navigation title menu & icons for commands
- Add position configuration entry
- Add new `reset-pet` event in webview
- Recalculate canvas size on window.resize event

### TODOs

- [x] bug: type color might not be normalized properly when resetting webview view

### CODE REVIEW

**Comment by tonybaloney** [comment]
@Yukaii this looks awesome! thanks so much for putting this together.

Let me know when its ready for review.

Just a note based on the videos. The "reset pets" shouldn't be the 🔄 icon, that's used for "refresh" in many panels, I think it would be confusing. Maybe the 🗑 icon if there is one?

**Comment by Yukaii** [comment]
Hi @tonybaloney it's ready for review now! 👍

**Comment by Vicente015** [comment]
I would like to try this to catch bugs and test it, I don't know about extension development in vscode what is the correct way to do it?

**Comment by tonybaloney** [comment]
@Vicente015 there is a launch.json in the project already so you have to 

- Run `npm install`
- Run `npm run compile`
- go to the debug panel in code and launch the development version with the extension loaded (first option in the debug profiles)

**Comment by tonybaloney** [comment]
If you want to save the steps as you learn them to the README as a PR to anyone else in future that would also be helpful!

**Comment by tonybaloney** [comment]
Tested it locally and it looks fantastic. The extension is so much more user friendly with button controls!

I did notice a bug though, if you open up the Preferences with the Explorer panel open and change the color of the pet it doesn't seem to push that to the panel?

Can you try that locally and let me know if you see the same behaviour

**Comment by Yukaii** [comment]
@tonybaloney Yes I found this behavior. It also happens to the latest `master` branch with panel webview. Should I change the behavior to just as the `reset-pets` command do?

**Comment by Vicente015** [comment]
I have tried this (thanks @tonybaloney) and it works great!

I have also noticed when you change the color of the pet or its type does not change until you click the reset pets button, the only thing that seems to change in real time is the size of the pet

vscode-pets bug

I have also noticed, if you move the pet panel to the sidebar it will show with an icon that seems to be the default, it would be great to change that icon

vscode-pets explorer icon

**Comment by tonybaloney** [comment]
@Yukaii per @Vicente015's comment about the default Icon, I've licensed an icon for use in this extension

**Comment by tonybaloney** [comment]
The file is in master if you rebase https://github.com/tonybaloney/vscode-pets/blob/master/media/animals.svg

**Comment by Yukaii** [comment]
### Dog & Cat (adjusted icon size to fit 600px without margin)

Screen Shot 2021-04-04 at 10 42 52 AM

### Cat person

Screen Shot 2021-04-04 at 10 32 49 AM

### Dog person

Screen Shot 2021-04-04 at 10 33 24 AM

**Comment by tonybaloney** [comment]
@Yukaii that looks awesome. Can you push the commit so I can review + merge

**Comment by Yukaii** [comment]
@tonybaloney I pushed the commits. The icon seems can not be switched dynamically, so I use `dog.svg` for now.

**Review by tonybaloney — APPROVED** [review]

**Comment by tonybaloney** [comment]
Very happy with this PR! thank you

**Pull request merged**
